# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MRtrix3
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mrtrix.org" # the base hostname & protocol for your site
permalink: pretty
author: "The MRtrix3 Team"
title_image: "/images/404/brain.png"
description: Advanced tools for the analysis of diffusion MRI data

# Build settings
markdown: kramdown

plugins_dir:
  - jekyll-redirect-from
